-- This is the RedG demo schema for H2 databases. Its use is to demonstrate features of RedG, it is not necessary a good schema you should use

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS CREDIT_CARD;
DROP TABLE IF EXISTS BANK_INSTITUTE;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS COUNTRY;

CREATE TABLE COUNTRY (
  COUNTRY_CODE VARCHAR2(3 CHAR)   NOT NULL PRIMARY KEY, // ISO 3166-1 ALPHA-3 code
  COUNTRY_NAME VARCHAR2(100 CHAR) NOT NULL,

  CONSTRAINT CHK_COUNTY CHECK (LENGTH(COUNTRY_CODE) = 3) // code has to be exactly 3 letters
);

CREATE TABLE ADDRESS (
  ADDRESS_ID   NUMBER(15)        NOT NULL PRIMARY KEY,

  COUNTRY_CODE VARCHAR2(3 CHAR)  NOT NULL,
  CITY         VARCHAR2(50 CHAR) NOT NULL,
  ZIPCODE      VARCHAR2(15 CHAR) NOT NULL,
  STREET       VARCHAR2(50 CHAR) NOT NULL,
  HOUSE_NUMBER VARCHAR2(8 CHAR)  NOT NULL,
  EXTRA        VARCHAR2(50 CHAR),

  CONSTRAINT FK_ADDRESS_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRY (COUNTRY_CODE)
);

CREATE TABLE BANK_INSTITUTE (
  BANK_ID   NUMBER(10)        NOT NULL PRIMARY KEY,
  BANK_NAME VARCHAR2(50 CHAR) NOT NULL,

  ADDRESS   NUMBER(15)        NOT NULL,
  -- yes, this is somewhat redundant. But simply imagine a Bank that serves customers only in Germany but has its headquarters in Denmark
  COUNTRY   VARCHAR2(3 CHAR)  NOT NULL,

  CONSTRAINT FK_BANK_INSTITUTE_ADDRESS FOREIGN KEY (ADDRESS) REFERENCES ADDRESS (ADDRESS_ID),
  CONSTRAINT FK_BANK_INSTITUTE_COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRY (COUNTRY_CODE)
);

CREATE TABLE CREDIT_CARD (
  CARD_NUMBER     NUMBER(16)         NOT NULL PRIMARY KEY,
  CVC             NUMBER(3)          NOT NULL,
  CARD_HOLDER     VARCHAR2(100 CHAR) NOT NULL,
  EXPIRATION_DATE TIMESTAMP          NOT NULL,
  ISSUING_BANK    NUMBER(10)         NOT NULL,

  CONSTRAINT CHK_CREDIT_CARD_NUMBER CHECK (CARD_NUMBER > 1000000000000000), //no cc has leading 0s
  CONSTRAINT FK_CREDIT_CARD_BANK FOREIGN KEY (ISSUING_BANK) REFERENCES BANK_INSTITUTE (BANK_ID)
);

CREATE TABLE CUSTOMER (
  CUSTOMER_ID     NUMBER(10)        NOT NULL PRIMARY KEY,
  LAST_NAME       VARCHAR2(50 CHAR) NOT NULL,
  FIRST_NAME      VARCHAR2(50 CHAR) NOT NULL,
  DATE_OF_BIRTH   TIMESTAMP         NOT NULL,
  ACCOUNT_CREATED TIMESTAMP         NOT NULL,

  ADDRESS         NUMBER(15),
  CREDIT_CARD     NUMBER(16)        NOT NULL,

  CONSTRAINT FK_CUSTOMER_ADDRESS FOREIGN KEY (ADDRESS) REFERENCES ADDRESS (ADDRESS_ID),
  CONSTRAINT FK_CUSTOMER_CREDIT_CARD FOREIGN KEY (CREDIT_CARD) REFERENCES CREDIT_CARD (CARD_NUMBER)
);

