-- 23.06.2017: Table student has changed! Use
-- ALTER TABLE REDGDEMO.STUDENT ADD NEEDS_STUDENT_AID NUMBER(1) DEFAULT 0 NOT NULL;
-- to migrate the schema. New users do NOT need to do this!

CREATE TABLESPACE REDGDEMO_TABSPACE
DATAFILE 'redg_tabspace.dat'
SIZE 5M AUTOEXTEND ON;

-- By default this user has 'password' as password but no session privilege (cannot log in)
-- If you want to use this user, edit the password before running this and grant session creation rights
CREATE USER REDGDEMO
IDENTIFIED BY PASSWORD
DEFAULT TABLESPACE REDGDEMO_TABSPACE;

-- GRANT CREATE SESSION TO REDGDEMO;
GRANT UNLIMITED TABLESPACE TO REDGDEMO;

CREATE TABLE REDGDEMO.STUDENT (
  STUDENT_ID        NUMBER(10)        NOT NULL PRIMARY KEY,
  FIRST_NAME        VARCHAR2(50 CHAR) NOT NULL,
  LAST_NAME         VARCHAR2(50 CHAR) NOT NULL,
  DATE_OF_BIRTH     TIMESTAMP         NOT NULL,
  NEEDS_STUDENT_AID NUMBER(1)         NOT NULL
);

CREATE TABLE REDGDEMO.CLASS (
  CLASS_ID NUMBER(6)         NOT NULL PRIMARY KEY,
  NAME     VARCHAR2(30 CHAR) NOT NULL
);

CREATE TABLE REDGDEMO.STUDENTS_IN_CLASSES (
  STUDENT_ID NUMBER(10) NOT NULL,
  CLASS_ID   NUMBER(6)  NOT NULL,
  PRIMARY KEY (STUDENT_ID, CLASS_ID),
  CONSTRAINT FK_STUDENTS_IN_CLASSES_STUDENTS FOREIGN KEY (STUDENT_ID) REFERENCES REDGDEMO.STUDENT (STUDENT_ID),
  CONSTRAINT FK_STUDENTS_IN_CLASSES_CLASSES FOREIGN KEY (CLASS_ID) REFERENCES REDGDEMO.CLASS (CLASS_ID)
);